# docker-compose.yml

services:
  # Serviço de Usuários (Python/FastAPI)
  usuarios-service:
    build:
      context: ./services/srv-usuarios
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./services/srv-usuarios:/code
    environment:
      - DATABASE_URL=postgresql://user:password@db-usuarios/mydatabase
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      db-usuarios:
        condition: service_healthy

  # Banco de Dados para o Serviço de Usuários
  db-usuarios:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_usuarios:/var/lib/postgresql/data
    # BLOCO ADICIONADO: Define como verificar a saúde do container do banco de dados.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  # API Gateway (Go)
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - usuarios-service

volumes:
  postgres_data_usuarios: