export enum DomainErrorCode {
  INVALID_TRANSITION = 'INVALID_TRANSITION',
  CONSULTATION_NOT_FOUND = 'CONSULTATION_NOT_FOUND',
  SLOT_UNAVAILABLE = 'SLOT_UNAVAILABLE',
  DEVICE_PERMISSION_DENIED = 'DEVICE_PERMISSION_DENIED',
  UNAUTHORIZED_ROOM_ACCESS = 'UNAUTHORIZED_ROOM_ACCESS',
}
