export enum ConsultationStatus {
  AGENDADA = 'AGENDADA',
  CANCELADA = 'CANCELADA',
  REALIZADA = 'REALIZADA',
  EM_ESPERA = 'EM_ESPERA',
  EM_ANDAMENTO = 'EM_ANDAMENTO',
  NAO_REALIZADA = 'NAO_REALIZADA',
}
